name: nahlachicken
description: "A new Flutter project."
publish_to: "none" # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  animations: ^2.0.11
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  esc_pos_utils_plus: ^2.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  get_it: ^8.0.3
  go_router: ^14.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconly: ^1.0.1
  image: 4.5.4
  intl: 0.19.0
  local_auth: ^2.3.0
  lottie: ^3.3.1
  permission_handler: ^12.0.0+1
  print_bluetooth_thermal: ^1.1.6
  share_plus: ^11.0.0
  toastification: ^3.0.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

# flutter_assets:
#   assets_path: assets/images
#   output_path: lib/core/utils
#   filename: assets.dart
#   field_prefix: null

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
